README.md
scripts/connected-start
scripts/connected-stop
scripts/start
scripts/stop

https://eaflood.atlassian.net/browse/FPD-480
Default to isolated start/stop and provide additional scripts for
running this service alongside others in the Mine Support stack.

Clarify start/stop scripts

---

README.md
helm/development-values.yaml
helm/templates/service.yaml
helm/values.yaml
scripts/exec
scripts/helm/install
scripts/start
scripts/stop
scripts/test

https://eaflood.atlassian.net/browse/PSD-120
Also, a minor script refactor in line with other FFC demo services.

Remove redundant Postgres service from dev deploys

---

Jenkinsfile
helm/ffc-demo-claim-service/templates/deployment.yaml

https://eaflood.atlassian.net/browse/PSD-231
Use a unique value for the redeployOnChange annotation to trigger pod
redeployment in Kubernetes on each deployment from the Jenkins build
pipeline.

Roll pods on every deployment from build pipeline

---

helm/ffc-demo-claim-service/templates/deployment.yaml
helm/ffc-demo-claim-service/templates/service.yaml

https://eaflood.atlassian.net/browse/PSD-315

Quoted all values as per Helm best practice advice

---

Jenkinsfile
package-lock.json
package.json

https://eaflood.atlassian.net/browse/PSD-412

Add SonarQube

---

README.md

https://eaflood.atlassian.net/browse/PSD-418

Remove Azure DevOps build badges from repo

---

Jenkinsfile

https://eaflood.atlassian.net/browse/PSD-458

psd-458 split test report

---

Jenkinsfile
package.json

https://eaflood.atlassian.net/browse/PSD-534

Update Jenkins library

---

Jenkinsfile
package.json

https://eaflood.atlassian.net/browse/PSD-504
Move to ffc-demo folder and making credentials consistent

Move to ffc-demo folder

---

Jenkinsfile
docker-compose.yaml
package.json

https://eaflood.atlassian.net/browse/PSD-539

Update pipeline for Non Production

---

helm/ffc-demo-claim-service/templates/deployment.yaml
helm/ffc-demo-claim-service/values.yaml
package.json

https://eaflood.atlassian.net/browse/PSD-532

Add pod priority

---

Jenkinsfile
README.md
docker-compose.override.yaml
docker-compose.yaml
helm/ffc-demo-claim-service/jenkins-aws.yaml
helm/ffc-demo-claim-service/production-values.yaml
helm/ffc-demo-claim-service/templates/deployment.yaml
helm/ffc-demo-claim-service/templates/service-account.yaml
helm/ffc-demo-claim-service/values.yaml
package-lock.json
package.json
server/config/mq-config.js

https://eaflood.atlassian.net/browse/PSD-570
Replace the individual queue access ID and secrets with a service
account with a trust relationship to the deployment

The demo service should use service accounts for SQS

---

package.json
server/migrations/20200417100059-add-email-column-to-claim.js
server/models/claim.js
test/claim-repository.test.js

https://eaflood.atlassian.net/browse/PSD-293
Add email field to the claim database table

Add email field to claim database table

---

README.md
docker-compose.override.yaml
docker-compose.yaml
helm/ffc-demo-claim-service/templates/_container.yaml
helm/ffc-demo-claim-service/values.yaml
jest.config.js
package-lock.json
package.json
server/config/index.js
server/config/mq-config.js
server/index.js
server/repository/claim-repository.js
server/schema/claimFromMessage.js
server/services/claim-message-action.js
server/services/claim-service.js
server/services/message-service.js
server/services/publish-message-action.js
test/claim-message-action.test.js
test/claim-service.test.js
test/index.test.js
test/integration/message-service.test.js

https://eaflood.atlassian.net/browse/PSD-292
Microservice receives a claim message so that the API gateway microservice can be removed

Receive claim message

---

Jenkinsfile
package.json

https://eaflood.atlassian.net/browse/PSD-738

PSD 738 libarary version updated

---

helm/ffc-demo-claim-service/templates/_container.yaml
helm/ffc-demo-claim-service/templates/config-map.yaml
helm/ffc-demo-claim-service/templates/container-sercret.yaml
helm/ffc-demo-claim-service/values.yaml
package.json

https://eaflood.atlassian.net/browse/PSD-765

PSD 765 Configmaps

---

README.md
docker-compose.yaml
helm/ffc-demo-claim-service/deployment-config-keys.txt
helm/ffc-demo-claim-service/templates/config-map.yaml
helm/ffc-demo-claim-service/templates/container-secret.yaml
helm/ffc-demo-claim-service/values.yaml
index.js
package-lock.json
package.json
server/services/app-insights.js

https://eaflood.atlassian.net/browse/PSD-821
Add app insights

Integrate app insights

---

.pre-commit-config.yaml
.secrets.baseline
.snyk
package.json

https://eaflood.atlassian.net/browse/PSD-614
Add pre-commit config file and secrets baseline

Add detect-secrets config

---

jest.config.js
package-lock.json
package.json
test/contract/claim.test.js
test/contract/schedule.test.js

https://eaflood.atlassian.net/browse/PSD-890

Add Pact Consumer test

---

test/asb-helper.js
test/contract/claim.test.js
test/db-helper.js
test/integration/local/message-service.test.js

- feat: clear ASB queues for tests

Clear messages in ASB queues created by tests

---

helm/ffc-demo-claim-service/templates/developer-rolebinding.yaml
package.json

https://eaflood.atlassian.net/browse/PSD-692

Rolebinding only on PR deployment

---

package-lock.json
package.json

- chore: increment version
- chore: increment version

House keeping

---

README.md
helm/ffc-demo-claim-service/values.yaml
package-lock.json
package.json
server/config/constants.js
server/config/database-config.js
server/config/index.js

- chore: increment version
- feat: use NODE_ENV to determine env for db creds

More robust env checking for db creds

---

package-lock.json
package.json
server/index.js
server/services/message-service.js
server/services/messaging/message-sender.js

- chore: increment version
- fix: catch and log error
- feat: move connection closing into message-service
- fix: module caching handles recreation

incremental improvements

---

.snyk
package-lock.json
package.json
provision.azure.yaml

https://eaflood.atlassian.net/browse/PSD-929

Fix Azure manifest

---

Dockerfile
Jenkinsfile
package-lock.json
package.json

https://eaflood.atlassian.net/browse/PSD-1009

Update parent image with CA cert

---

.snyk
package-lock.json
package.json

https://eaflood.atlassian.net/browse/PSD-978

Remove unnecessary snyk ignores

---

package-lock.json
package.json
server/services/app-insights.js

https://eaflood.atlassian.net/browse/PSD-924

Log when App Insights is active 

---

.snyk
package-lock.json
package.json
server/services/database-service.js

https://eaflood.atlassian.net/browse/PSD-1023

Upgrade Sequelize

---

package-lock.json
package.json

https://eaflood.atlassian.net/browse/PSD-1265

Fix dependabot vulnerabilities

---

package-lock.json
package.json
test/db-helper.js

This pr includes the below changes to update dependent packages to the latest version
https://dev.azure.com/defragovuk/DEFRA-FFC/_workitems/edit/231573

231573: Updating dependency packages

---

.azuredevops/build.yaml
app/config/database-config.js
helm/ffc-demo-claim-service/Chart.yaml
helm/ffc-demo-claim-service/templates/config-map.yaml
helm/ffc-demo-claim-service/templates/container-secret.yaml
helm/ffc-demo-claim-service/templates/deployment.yaml
helm/ffc-demo-claim-service/templates/developer-rolebinding.yaml
helm/ffc-demo-claim-service/values.yaml
package-lock.json
package.json

This pr includes the changes to update helm charts for ADP and added ADO build pipeline.
https://dev.azure.com/defragovuk/DEFRA-FFC/_workitems/edit/231730

231730: Updated helm charts for ADP and added ADO build pipeline

---

.azuredevops/build.yaml
appConfig/appConfig.snd2.json
appConfig/appConfig.snd3.json
package-lock.json
package.json

This PR contains the changes to update app config.json for snd2 and snd3.
[AB#262177](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/262177)

262177: updated app config and package

---

db-migration.Dockerfile
scripts/migration/database-up

[AB#262177](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/262177)

262177: reverted dockerfile and script

---

db-migration.Dockerfile

[AB#262177](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/262177)

262177: fix

---

.azuredevops/build.yaml
db-migration.Dockerfile
package-lock.json
package.json
scripts/migration/database-up

This PR contains the changes to Retrieve Access Token for DB Migrations using Workload Identity
[AB#260861](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/260861)

260861: Retrieve Access Token for DB Migrations using Workload Identity

---

appConfig/appConfig.dev1.json
appConfig/appConfig.tst1.json
package-lock.json
package.json

Added Dev and Tst config file forffc-demo-claim-service

261316: Dev and Tst config file

---

.azuredevops/build.yaml
catalog-info.yaml

Default Component added to ref techdocs

279550  : techdocs

---

helm/ffc-demo-claim-service/values.yaml
package-lock.json
package.json

Removed duplicate values defined in the values.yaml files.   Also removed values which are the same as the defaults in the helm-library.
Information defined in the app config files will not be duplicated in the values.yaml file
Tested changes against SND1 Cluster and Demo Apps are still working successfully.

277457: Remove duplicate values defined in the values.yaml files for each repo

---

catalog-info.yaml
package.json

[AB#296543](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/296543)
1. Updated component details for the common documentation portal
2. Fixed the CI pipeline name
Added unit tests
- [] This PR contains tests

296543: Techdocs Update

---

db-migration.Dockerfile
docker-compose.migrate.yaml
package-lock.json
package.json
scripts/migration/database-up

This PR contains the changes to fix db migration for local development
[AB#299229](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/299229)

299229: fix db migration for local development

---

README.md
helm/ffc-demo-claim-service/Chart.yaml
helm/ffc-demo-claim-service/values.yaml
package-lock.json
package.json

Helm cleanup and Readme updates

Helm cleanup and Readme updates

---

.azuredevops/build.yaml
package.json

*A brief description of changes being made*
*Link to the relevant work items: 
[AB#323021](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/323021)
Simplify the variable import from variable groups specific to environment
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=498614&view=results
Have you updated any related templates, repositories or dependencies for new changes? We must ensure any dependencies like Software Templates are updated to include the latest changes to be scaffolded for all services where applicable.

323021: Variable import

---

.pre-commit-config.yaml
package.json

Update pre-commit version to the latest version 1.4
*Link to the relevant work items: e.g: Relates to ADO Work Item [AB#338671](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/338671) and builds on #3376 (link to ADO Build ID URL)*

338671: Updated the version of Yelp to v1.4.0

---

.azuredevops/build.yaml
appConfig/appConfig.snd4.yaml
package.json

Added snd4 file into appConfig folder, updated postgres_db value to fcp-demo-claim
[AB#334259](https://dev.azure.com/defragovuk/DEFRA-FFC/_sprints/taskboard/DEFRA-FFC%20Team%20Fab/DEFRA-FFC/Platform/Fab/Sprint16?workitem=334259)

33429: snd4 appConfig

---

.azuredevops/build.yaml
db-migration.Dockerfile
package.json

Use Postgres Db migrations base image. 
[AB#400560](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/400560)

400560: DB migration image

---

package.json

Increment version because there are existing deployments from features branches in SND3 and SND4 for v5.2.6
*Link to the relevant work items: e.g: Relates to ADO Work Item [AB#397803](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/397803)

397803: Increment version to 5.2.6

---

appConfig/appConfig.dev1.yaml
appConfig/appConfig.prd1.yaml
appConfig/appConfig.pre1.yaml
appConfig/appConfig.snd3.yaml
appConfig/appConfig.tst1.yaml
appConfig/appConfig.tst2.yaml
package.json

*A brief description of changes being made*
*Link to the relevant work items: e.g: Relates to ADO Work Item [AB#213700](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/213700) and builds on #3376 (link to ADO Build ID URL)*

Updated config
